### ISSUE TITLE
I cant run synergydatagrid

### ISSUE THREAD

**Issue by cincarnato** [odiaseo/zf2-datagrid#44]
several problems:

---

1.When installed by composer fails that require synbergy / common. 
## \- Ok, I add synergy / common

2.When attempting to use the datagrid encounter several warnings and exception:

Controller:
////////////////////////////////////////////////
 public function gridAction() {
//replace {Entity_Name} with your entity name e.g. 'Application\Entity\User'
$serviceManager = $this->getServiceLocator();
$grid = $serviceManager->get('jqgrid')->setGridIdentity("\DBAL\Entity\ScanManager");

```
    return array('grid' => $grid);
}
```

////////////////////////////////////////////////

Warning: file_put_contents(data/SynergyDataGrid/cache/orm_entity_classmap.php) [function.file-put-contents]: failed to open stream: No such file or directory in /home/security/www/App/vendor/synergy/common/lib/SynergyCommon/Service/BaseService.php on line 350

Warning: include(data/SynergyDataGrid/cache/orm_entity_classmap.php) [function.include]: failed to open stream: No such file or directory in /home/security/www/App/vendor/synergy/common/lib/SynergyCommon/Service/BaseService.php on line 363

Warning: include() [function.include]: Failed opening 'data/SynergyDataGrid/cache/orm_entity_classmap.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in /home/security/www/App/vendor/synergy/common/lib/SynergyCommon/Service/BaseService.php on line 363

Warning: array_search() expects parameter 2 to be array, boolean given in /home/security/www/App/vendor/synergy/common/lib/SynergyCommon/Service/BaseService.php on line 365
-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Exception:

Zend\Mvc\Router\Exception\InvalidArgumentException
File:
/home/security/www/App/vendor/zendframework/zendframework/library/Zend/Mvc/Router/Http/Segment.php:298
Message:
Missing parameter "entity"
-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
1. do some ugly fixes
   ------------..............--------------
   Add include path in controller:
   set_include_path("/home/security/www/App/vendor/synergy/synergydatagrid/");
   ------------..............--------------
   Add in BaseService.php:

protected function _createEntityCache($filename)
    {  
        $filename = "/home/security/www/App/vendor/synergy/".$filename; //<--
------------..............--------------
1. I have this exception:

Zend\ServiceManager\Exception\ServiceNotCreatedException
File:
/home/security/www/App/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php:1070
Message:
An abstract factory could not create an instance of synergydatagridmodel(alias: synergydatagrid\model).

------------..............--------------

Can you help me?

**Comment by ellipee** [comment]
how can i replace my icons to use fontawesome please
