### ISSUE TITLE
error on edit, delete and add new record

### ISSUE THREAD

**Issue by ellipee** [odiaseo/zf2-datagrid#56]
please i have some questions regarding the use and customization of this module, i installed and configure this module and it render well in my project, but i have the following questions and hoping for some solutions.
1. when i want to add, edit or delete my record i see the this error message "error Status: 'Not Found'. Error code: 404"
2. how can i set the module such that it switch to editing mode by double clicking on a row
3. where should i put the following code in order to remove and add customize class to the grid

// remove classes
$(".ui-jqgrid").removeClass("ui-widget ui-widget-content");
$(".ui-jqgrid-view").children().removeClass("ui-widget-header ui-state-default");
$(".ui-jqgrid-labels, .ui-search-toolbar").children().removeClass("ui-state-default ui-th-column ui-th-ltr");
$(".ui-jqgrid-pager").removeClass("ui-state-default");
$(".ui-jqgrid").removeClass("ui-widget-content");

            // add classes
            $(".ui-jqgrid-htable").addClass("table table-bordered table-hover");
            $(".ui-jqgrid-btable").addClass("table table-bordered table-striped");

            $(".ui-pg-div").removeClass().addClass("btn btn-sm btn-primary");
            $(".ui-icon.ui-icon-plus").removeClass().addClass("fa fa-plus");
            $(".ui-icon.ui-icon-pencil").removeClass().addClass("fa fa-pencil");
            $(".ui-icon.ui-icon-trash").removeClass().addClass("fa fa-trash-o");
            $(".ui-icon.ui-icon-search").removeClass().addClass("fa fa-search");
            $(".ui-icon.ui-icon-refresh").removeClass().addClass("fa fa-refresh");
            $(".ui-icon.ui-icon-disk").removeClass().addClass("fa fa-save").parent(".btn-primary").removeClass("btn-primary").addClass("btn-success");
            $(".ui-icon.ui-icon-cancel").removeClass().addClass("fa fa-times").parent(".btn-primary").removeClass("btn-primary").addClass("btn-danger");

            $(".ui-icon.ui-icon-seek-prev").wrap("<div class='btn btn-sm btn-default'></div>");
            $(".ui-icon.ui-icon-seek-prev").removeClass().addClass("fa fa-backward");

            $(".ui-icon.ui-icon-seek-first").wrap("<div class='btn btn-sm btn-default'></div>");
            $(".ui-icon.ui-icon-seek-first").removeClass().addClass("fa fa-fast-backward");

            $(".ui-icon.ui-icon-seek-next").wrap("<div class='btn btn-sm btn-default'></div>");
            $(".ui-icon.ui-icon-seek-next").removeClass().addClass("fa fa-forward");

            $(".ui-icon.ui-icon-seek-end").wrap("<div class='btn btn-sm btn-default'></div>");
            $(".ui-icon.ui-icon-seek-end").removeClass().addClass("fa fa-fast-forward");

please i am completely new to jqgrid but i am determine to learn and use it.
thank you very much in anticipation of your quick response.

**Comment by t0F** [comment]
Hi, you will probably have to wait odiaseo for better answers, but : 

1 - looks like your crudAction method is missing (see main page for more details)

2 - If there is no option for that (i don't know), you can put a JS event when all data are loaded. In that event, put a for loop on every row in order to add an event on double click. In that event, call the edit action. 


3 - you could probably put an event on the jqgrid (onload or something like that) and put your code in that. 

I'm not on the same projects anymore, but if you have trouble with onload event I will take a look how we did that.

Good luck
