### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by adarshkhatri** [odiaseo/zf2-datagrid#59]
I have added `"synergy/synergydatagrid": "dev-master"` in my `composer.json` file 

When I do `composer update` it gives me below error. What am I doing wrong?

> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Installation request for synergy/synergydatagrid dev-master -> satisfiable by synergy/synergydatagrid[dev-master].
>     - synergy/synergydatagrid dev-master requires synergy/common 1.0.x-dev -> satisfiable by synergy/common[1.0.x-dev] but these conflict with your requirements or minimum-stability.

**Comment by odiaseo** [comment]
Can you update the minimum stability config in composer.json ```minimum-stability": "dev"```
